### ISSUE TITLE
Widget details url

### ISSUE THREAD

**Issue by mg6maciej** [Userfeeds/android-ads-sdk#3]

**Comment by gkapkowski** [comment]
http://userfeeds.io/apps/widgets/details/?context=network:0xmyaddress12345667b&algorithm=algo&whitelist=whitelist

**Comment by gkapkowski** [comment]
@mg6maciej the url will be online after https://github.com/Userfeeds/Apps/pull/2 is resolved

**Comment by mg6maciej** [comment]
Would prefer singular http://userfeeds.io/apps/widget/details, so user can read from url that it belongs to single "widget".
